model:
  type: "distilbert"
  name: "distilbert-base-uncased"
  num_labels: 4

dataset:
  name: "ag_news"
  total_samples: 3000
  split: "train"

training:
  epochs: 3
  batch_size: 32
  micro_batch_size: 4
  sync_every: 5
  learning_rate: 5e-5
  report_step: 40

workers:
  num_workers: 2
  master_host: "master-service"
  master_port: 50051
  pvc_name: "server-pvc"